version: '3.8'

services:
  springboot-app:
    image: smartoothai-api-main-springboot-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    restart: always
    user: "appuser"

networks:
  app-network:
    driver: bridge
